### PR TITLE
GameMaker:Studio 2.3+ compatibility (auto-converted)

### PR DESCRIPTION
**Pull request by gnysek**
I've prepared a script which converted most of functions to 2.3 format. There might be some bugs, as converting functions with argument_count wasn't that easy, but mostly 90% is done.

### CODE REVIEW

**Comment by xotmatrix** [comment]
Thank you, gnysek. I appreciate you taking the time to work on this but I cannot merge this pull request. There too many errors and the scripts require additional formatting tweaks. An update for 2.3 is going to have to be a largely manual job on a fresh repo. 

There are also some issues with the way the GMLscripts.com site works that have to be resolved before it can correctly display scripts in a new format. Script pages and indices are dynamically generated from the script repo and it expects scripts to follow certain rules. 

Thanks for your efforts. Sorry if my inaction has wasted your time. I'll try to channel my embarrassment into productive updates.

**Comment by xotmatrix** [comment]
I have cloned a local copy of your changes because their utility may exceed my stubborness. Thanks again.

**Comment by gnysek** [comment]
That's what I meant - to inspire you :P

**Comment by xotmatrix** [comment]
This is starting to progress. It's a slow process. I'm not just reformatting scripts, I'm creating tests for each of them. Nevertheless, I was getting through them at a decent rate until I hurt my back. Sitting to type has been excruciating for a couple of weeks. I'm still having some nerve pain but things are much better now. I think I can continue converting scripts this weekend.

**Comment by gnysek** [comment]
How is it going with 2.3+ conversion ? :) Lot of new features was added since 2021...

**Comment by xotmatrix** [comment]
I've updated many scripts (about 50 in the last 30 days, around 90 overall) and have many more to go. It doesn't take long to update the scripts but the test cases I'm creating for them to ensure these changes (and future ones) work correctly take 100 times as long. I needed to take an RSI break last week but I'm going to do some more sections this weekend.

My time has been somewhat divided between script updates and updates to site function.

**Comment by xotmatrix** [comment]
GitHub, I don't appreciate you tattling about force-pushes. That's supposed to be a secret.

**Pull request closed without merging**
